### ISSUE TITLE
Simple Rando Mutation Erro de índice.

### ISSUE THREAD

**Issue by gleydson404** [gleydson404/GA-CVRP#8]
```
> Traceback (most recent call last):
>   File "GACRVP.py", line 544, in <module>
>     main()
>   File "GACRVP.py", line 538, in main
>     qtd_vehicles, demands, capacity, gama, size_ind, fit_pop)
>   File "GACRVP.py", line 493, in evolve
>     child = simple_mutation(child, dist_matrix, qtd_vehicles)
>   File "GACRVP.py", line 342, in simple_mutation
>     rota.insert(posicao[1], cliente)
> IndexError: list index out of range
```

@Donegas

**Comment by Donegas** [comment]
.
Funcionando

**Comment by AlexRogaleski** [comment]
[srm e cr.txt](https://github.com/gleydson404/GA-CVRP/files/314929/srm.e.cr.txt)
